### ISSUE TITLE
Experiment Manager

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#105]
We need a tool that makes it easy to specify multi-factorial experiments and deploy them to the cloud. We can re-use a utility I developed in the past as a starting place:

https://github.com/colinsheppard/abmutils/blob/master/src/main/java/abmutils/experiment/

This works by creating an experiment file (in yaml format). Here's an example:

```
Author: Andy
Title: Verify-Nest-Initiation
InputsDirectory: modeling-notebook/model-inputs/
OutputsDirectory: ternpop_verification/
Replicates: 2
NonDefaults:
- Logfiles: Tern,Site,Event,Nest
- NumThreads: 1
Factors:
- Code: MaxBreedingAttempts
  Levels:
  - Code: Normal
    Params:
    - MaxNumBreedingAttempts: 2
  - Code: Extended
    Params:
    - MaxNumBreedingAttempts: 3
- Code: MortalityProbability
  Levels:
  - Code: Low
    Params:
    - MortalityProbability: 0.1
  - Code: High
    Params:
    - MortalityProbability: 0.2
```

The key component to this is the "Factors". In this example there are 2 factors, MaxBreedingAttempts and MortalityProbability, each with 2 levels. The experiment manager's job is to configure and run the model for every combination of factors (in this case 4 times). In addition there is a Replicates field that means the model will be re-run multiple times with different random seeds as the starting place. While actually using Replicates may be overkill for BEAM, we should keep that functionality. 

The NonDefaults field is a way to quickly override a config parameter's default value for the entirety of an experiment (without needing to modify the base conf file).

**How BEAM Experiment Manager will be different**

The experiment manager I created was designed to run serially within one session. Our manager needs to enable cloud deployment. More to come on this...
